### ISSUE TITLE
Docs problems

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#3]
* `InfoDialog` uses class "`Header`" which has `subTitle`, but in reality, `Header.Default` has no subtitle
* Datetime artifact name is wrong, it's `date-time`, not `date_time`
* Not all properties of duration dialogs are documented. For example, `displayClearButton`
* Notion is a good choice, but the page is super laggy (notion is prone to performance issues). I suggest moving everything into collapsible subheaders.
* `CalendarSample.kt` etc. should be clickable links to files, not just text (where do I find them??)

**Comment by maxkeppeler** [comment]
Thanks for the info! 
1. The `Header` class has no property `subTitle` - where does that come from? I can't find this String anywhere in the project. 🤔 
2. Will be corrected.
3. I'm not sure if I'm missing anything, but the class has kdocs:
```
/**
 * The general configuration for the duration dialog.
 * @param timeFormat Available color selection modes. If null, both are used.
 * @param currentTime Current time in seconds.
 * @param minTime Minimum time.
 * @param maxTime Maximum time.
 * @param displayClearButton Replaces the "00" Value-Button with a button to clear all values.            <----
 */
data class DurationConfig(
    val timeFormat: DurationFormat = DurationFormat.MM_SS,
    val currentTime: Long? = null,
    val minTime: Long = 0,
    val maxTime: Long = Long.MAX_VALUE,
    val displayClearButton: Boolean = false
) : BaseConfigs()
```
But yes. The documentation still needs to improved (Readme and Kdocs). That's also why it currently only got a b-rating from codacy. 
4. I first did the documentation in the README.md file but then switched to Notion because it's just quicker, easier and more dynamic & comfortable for so much information. I could only feel a slight lag when loading the page initially. I will see what I can do. The GIFs are probably slowing down the page mainly. 
5. They are the in app-module in the package `samples`. That was my intention that I forgot in the process. I will link the file names.

**Comment by Nek-12** [comment]
Alright, I think you can close this then if you think it's done
